// Supplemental translations for beta UI surfaces whose keys do not exist in
// the older locale JSON packs yet. Existing locale JSON values still win.
const packs = {
  zh: {
    terminal: '终端', terminalSubtitle: '集成 Shell、Runner 和 AI 助手', newTerminal: '新建终端', chooseShell: '选择 Shell 配置', noTerminal: '没有正在运行的终端', startApproved: '点击 + 或选择 Shell 配置，在已授权工作区中启动。', terminalWindow: 'OrPAD 终端', loadingWorkspace: '正在加载工作区...', dockMain: '停靠到主窗口', noWorkspace: '尚无已授权工作区',
    aiReady: 'AI 侧边栏已就绪。', aiReadyDoc: 'AI 已准备好处理 {name}', aiDocPrompt: '可基于当前文档请求改写、解释或格式转换。', aiGeneralPrompt: '可以直接提问，或打开文档以附加文件上下文。', noActive: '没有活动文档。聊天仍可使用；打开文件后可附加文档上下文。', providerSettings: 'AI Provider 设置', newChat: '新建聊天', rename: '重命名', search: '搜索', send: '发送', stop: '停止', waiting: '正在等待 AI 响应...', assist: '辅助工具', noActiveTitle: '没有活动文档。', openDocTools: '打开 CSV、JSON、Markdown 或 Mermaid 标签页后可查看本地和 AI 辅助工具。',
    mcpServers: 'MCP 服务器', mcpSubtitle: '启用服务器后打开 Tools 或 Resources。工具调用始终需要权限确认。', desktopOnly: 'MCP 仅限桌面版。', desktopOnlyBody: '打开 Electron 应用以连接本地 MCP 服务器。', noMcp: '尚未配置 MCP 服务器。', addImport: '添加服务器或导入 MCP 配置即可开始。', refresh: '刷新', add: '添加', edit: '编辑', export: '导出', import: '导入', enable: '启用', disable: '禁用', running: '运行中', starting: '启动中', stopped: '已停止',
  },
  'zh-TW': {
    terminal: '終端機', terminalSubtitle: '整合 Shell、Runner 與 AI 助手', newTerminal: '新增終端機', chooseShell: '選擇 Shell 設定檔', noTerminal: '沒有執行中的終端機', startApproved: '按 + 或選擇 Shell 設定檔，在已授權工作區啟動。', terminalWindow: 'OrPAD 終端機', loadingWorkspace: '正在載入工作區...', dockMain: '停靠到主視窗', noWorkspace: '尚無已授權工作區',
    aiReady: 'AI 側邊欄已就緒。', aiReadyDoc: 'AI 已準備好處理 {name}', aiDocPrompt: '可使用目前文件作為脈絡，要求改寫、說明或格式轉換。', aiGeneralPrompt: '可以直接提問，或開啟文件以附加檔案脈絡。', noActive: '沒有作用中的文件。聊天仍可使用；開啟檔案即可附加文件脈絡。', providerSettings: 'AI Provider 設定', newChat: '新增聊天', rename: '重新命名', search: '搜尋', send: '傳送', stop: '停止', waiting: '正在等待 AI 回應...', assist: '輔助工具', noActiveTitle: '沒有作用中的文件。', openDocTools: '開啟 CSV、JSON、Markdown 或 Mermaid 分頁後可查看本機與 AI 輔助工具。',
    mcpServers: 'MCP 伺服器', mcpSubtitle: '啟用伺服器後開啟 Tools 或 Resources。工具呼叫一律需要權限確認。', desktopOnly: 'MCP 僅限桌面版。', desktopOnlyBody: '開啟 Electron 應用程式以連接本機 MCP 伺服器。', noMcp: '尚未設定 MCP 伺服器。', addImport: '新增伺服器或匯入 MCP 設定即可開始。', refresh: '重新整理', add: '新增', edit: '編輯', export: '匯出', import: '匯入', enable: '啟用', disable: '停用', running: '執行中', starting: '啟動中', stopped: '已停止',
  },
  ja: {
    terminal: 'ターミナル', terminalSubtitle: '統合シェル、Runner、AI ヘルパー', newTerminal: '新しいターミナル', chooseShell: 'シェルプロファイルを選択', noTerminal: '実行中のターミナルはありません', startApproved: '+ をクリックするかシェルプロファイルを選択して、承認済みワークスペースで開始します。', terminalWindow: 'OrPAD ターミナル', loadingWorkspace: 'ワークスペースを読み込み中...', dockMain: 'メインにドッキング', noWorkspace: '承認済みワークスペースはまだありません',
    aiReady: 'AI サイドバーの準備ができました。', aiReadyDoc: '{name} に対して AI の準備ができました', aiDocPrompt: '現在の文書をコンテキストにして、書き換え、説明、形式変換を依頼できます。', aiGeneralPrompt: '一般的な質問をするか、文書を開いてファイルコンテキストを添付できます。', noActive: 'アクティブな文書はありません。チャットは利用できます。ファイルを開くと文書コンテキストを添付できます。', providerSettings: 'AI Provider 設定', newChat: '新規チャット', rename: '名前変更', search: '検索', send: '送信', stop: '停止', waiting: 'AI の応答を待機中...', assist: 'Assist ツール', noActiveTitle: 'アクティブな文書はありません。', openDocTools: 'CSV、JSON、Markdown、Mermaid タブを開くと、ローカルおよび AI Assist ツールが表示されます。',
    mcpServers: 'MCP サーバー', mcpSubtitle: 'サーバーを有効化してから Tools または Resources を開きます。ツール呼び出しには常に権限確認が必要です。', desktopOnly: 'MCP はデスクトップ専用です。', desktopOnlyBody: 'ローカル MCP サーバーに接続するには Electron アプリを開いてください。', noMcp: 'MCP サーバーが設定されていません。', addImport: 'サーバーを追加するか MCP 設定をインポートして開始します。', refresh: '更新', add: '追加', edit: '編集', export: 'エクスポート', import: 'インポート', enable: '有効化', disable: '無効化', running: '実行中', starting: '起動中', stopped: '停止中',
  },
  es: {
    terminal: 'Terminal', terminalSubtitle: 'Shell integrado, Runner y asistentes de IA', newTerminal: 'Nuevo terminal', chooseShell: 'Elige un perfil de shell', noTerminal: 'No hay terminal en ejecución', startApproved: 'Haz clic en + o elige un perfil de shell para iniciar en el workspace aprobado.', terminalWindow: 'Terminal de OrPAD', loadingWorkspace: 'Cargando workspace...', dockMain: 'Acoplar a la ventana principal', noWorkspace: 'Aún no hay workspace aprobado',
    aiReady: 'La barra lateral de IA está lista.', aiReadyDoc: 'La IA está lista para {name}', aiDocPrompt: 'Pide una reescritura, explicación o transformación usando el documento actual como contexto.', aiGeneralPrompt: 'Haz una pregunta general o abre un documento para adjuntar contexto de archivo.', noActive: 'No hay documento activo. El chat sigue funcionando; abre un archivo para adjuntar contexto.', providerSettings: 'Configuración de AI Provider', newChat: 'Nuevo chat', rename: 'Renombrar', search: 'Buscar', send: 'Enviar', stop: 'Detener', waiting: 'Esperando respuesta de IA...', assist: 'Herramientas Assist', noActiveTitle: 'No hay documento activo.', openDocTools: 'Abre una pestaña CSV, JSON, Markdown o Mermaid para ver herramientas locales y de IA.',
    mcpServers: 'Servidores MCP', mcpSubtitle: 'Activa un servidor y luego abre Tools o Resources. Las llamadas a herramientas siempre requieren permiso.', desktopOnly: 'MCP solo está disponible en escritorio.', desktopOnlyBody: 'Abre la app Electron para conectar servidores MCP locales.', noMcp: 'No hay servidores MCP configurados.', addImport: 'Agrega un servidor o importa una configuración MCP para empezar.', refresh: 'Actualizar', add: 'Agregar', edit: 'Editar', export: 'Exportar', import: 'Importar', enable: 'Activar', disable: 'Desactivar', running: 'En ejecución', starting: 'Iniciando', stopped: 'Detenido',
  },
  fr: {
    terminal: 'Terminal', terminalSubtitle: 'Shell intégré, Runner et assistants IA', newTerminal: 'Nouveau terminal', chooseShell: 'Choisir un profil shell', noTerminal: 'Aucun terminal en cours', startApproved: 'Cliquez sur + ou choisissez un profil shell pour démarrer dans l’espace de travail approuvé.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Chargement de l’espace de travail...', dockMain: 'Ancrer à la fenêtre principale', noWorkspace: 'Aucun espace de travail approuvé',
    aiReady: 'La barre latérale IA est prête.', aiReadyDoc: 'L’IA est prête pour {name}', aiDocPrompt: 'Demandez une réécriture, une explication ou une transformation avec le document actuel comme contexte.', aiGeneralPrompt: 'Posez une question générale ou ouvrez un document pour joindre son contexte.', noActive: 'Aucun document actif. Le chat fonctionne toujours ; ouvrez un fichier pour joindre le contexte du document.', providerSettings: 'Paramètres AI Provider', newChat: 'Nouveau chat', rename: 'Renommer', search: 'Rechercher', send: 'Envoyer', stop: 'Arrêter', waiting: 'En attente de la réponse IA...', assist: 'Outils Assist', noActiveTitle: 'Aucun document actif.', openDocTools: 'Ouvrez un onglet CSV, JSON, Markdown ou Mermaid pour voir les outils locaux et IA.',
    mcpServers: 'Serveurs MCP', mcpSubtitle: 'Activez un serveur, puis ouvrez Tools ou Resources. Les appels d’outils demandent toujours une autorisation.', desktopOnly: 'MCP est réservé à l’application desktop.', desktopOnlyBody: 'Ouvrez l’application Electron pour connecter des serveurs MCP locaux.', noMcp: 'Aucun serveur MCP configuré.', addImport: 'Ajoutez un serveur ou importez une configuration MCP pour commencer.', refresh: 'Actualiser', add: 'Ajouter', edit: 'Modifier', export: 'Exporter', import: 'Importer', enable: 'Activer', disable: 'Désactiver', running: 'En cours', starting: 'Démarrage', stopped: 'Arrêté',
  },
  de: {
    terminal: 'Terminal', terminalSubtitle: 'Integrierte Shell, Runner und KI-Helfer', newTerminal: 'Neues Terminal', chooseShell: 'Shell-Profil auswählen', noTerminal: 'Kein Terminal läuft', startApproved: 'Klicke auf + oder wähle ein Shell-Profil, um im freigegebenen Workspace zu starten.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Workspace wird geladen...', dockMain: 'An Hauptfenster andocken', noWorkspace: 'Noch kein freigegebener Workspace',
    aiReady: 'Die KI-Seitenleiste ist bereit.', aiReadyDoc: 'KI ist bereit für {name}', aiDocPrompt: 'Bitte um Umschreiben, Erklärung oder Formatumwandlung mit dem aktuellen Dokument als Kontext.', aiGeneralPrompt: 'Stelle eine allgemeine Frage oder öffne ein Dokument, um Dateikontext anzuhängen.', noActive: 'Kein aktives Dokument. Chat funktioniert weiterhin; öffne eine Datei, um Dokumentkontext anzuhängen.', providerSettings: 'AI Provider-Einstellungen', newChat: 'Neuer Chat', rename: 'Umbenennen', search: 'Suchen', send: 'Senden', stop: 'Stopp', waiting: 'Warte auf KI-Antwort...', assist: 'Assist-Tools', noActiveTitle: 'Kein aktives Dokument.', openDocTools: 'Öffne einen CSV-, JSON-, Markdown- oder Mermaid-Tab, um lokale und KI-Assist-Tools zu sehen.',
    mcpServers: 'MCP-Server', mcpSubtitle: 'Aktiviere einen Server und öffne dann Tools oder Resources. Tool-Aufrufe benötigen immer eine Berechtigung.', desktopOnly: 'MCP ist nur in der Desktop-App verfügbar.', desktopOnlyBody: 'Öffne die Electron-App, um lokale MCP-Server zu verbinden.', noMcp: 'Keine MCP-Server konfiguriert.', addImport: 'Füge einen Server hinzu oder importiere eine MCP-Konfiguration.', refresh: 'Aktualisieren', add: 'Hinzufügen', edit: 'Bearbeiten', export: 'Exportieren', import: 'Importieren', enable: 'Aktivieren', disable: 'Deaktivieren', running: 'Läuft', starting: 'Startet', stopped: 'Gestoppt',
  },
  pt: {
    terminal: 'Terminal', terminalSubtitle: 'Shell integrada, Runner e assistentes de IA', newTerminal: 'Novo terminal', chooseShell: 'Escolha um perfil de shell', noTerminal: 'Nenhum terminal em execução', startApproved: 'Clique em + ou escolha um perfil de shell para iniciar no workspace aprovado.', terminalWindow: 'Terminal do OrPAD', loadingWorkspace: 'Carregando workspace...', dockMain: 'Acoplar à janela principal', noWorkspace: 'Nenhum workspace aprovado ainda',
    aiReady: 'A barra lateral de IA está pronta.', aiReadyDoc: 'A IA está pronta para {name}', aiDocPrompt: 'Peça uma reescrita, explicação ou transformação usando o documento atual como contexto.', aiGeneralPrompt: 'Faça uma pergunta geral ou abra um documento para anexar contexto.', noActive: 'Nenhum documento ativo. O chat ainda funciona; abra um arquivo para anexar contexto.', providerSettings: 'Configurações de AI Provider', newChat: 'Novo chat', rename: 'Renomear', search: 'Pesquisar', send: 'Enviar', stop: 'Parar', waiting: 'Aguardando resposta da IA...', assist: 'Ferramentas Assist', noActiveTitle: 'Nenhum documento ativo.', openDocTools: 'Abra uma aba CSV, JSON, Markdown ou Mermaid para ver ferramentas locais e de IA.',
    mcpServers: 'Servidores MCP', mcpSubtitle: 'Ative um servidor e abra Tools ou Resources. Chamadas de ferramentas sempre exigem permissão.', desktopOnly: 'MCP está disponível apenas no desktop.', desktopOnlyBody: 'Abra o app Electron para conectar servidores MCP locais.', noMcp: 'Nenhum servidor MCP configurado.', addImport: 'Adicione um servidor ou importe uma configuração MCP para começar.', refresh: 'Atualizar', add: 'Adicionar', edit: 'Editar', export: 'Exportar', import: 'Importar', enable: 'Ativar', disable: 'Desativar', running: 'Em execução', starting: 'Iniciando', stopped: 'Parado',
  },
  ru: {
    terminal: 'Терминал', terminalSubtitle: 'Встроенная shell, Runner и AI-помощники', newTerminal: 'Новый терминал', chooseShell: 'Выберите профиль shell', noTerminal: 'Нет запущенного терминала', startApproved: 'Нажмите + или выберите профиль shell для запуска в разрешённой рабочей области.', terminalWindow: 'Терминал OrPAD', loadingWorkspace: 'Загрузка рабочей области...', dockMain: 'Закрепить в главном окне', noWorkspace: 'Разрешённой рабочей области пока нет',
    aiReady: 'Боковая панель AI готова.', aiReadyDoc: 'AI готов для {name}', aiDocPrompt: 'Попросите переписать, объяснить или преобразовать формат с текущим документом как контекстом.', aiGeneralPrompt: 'Задайте общий вопрос или откройте документ, чтобы добавить файловый контекст.', noActive: 'Нет активного документа. Чат всё ещё работает; откройте файл, чтобы добавить контекст документа.', providerSettings: 'Настройки AI Provider', newChat: 'Новый чат', rename: 'Переименовать', search: 'Поиск', send: 'Отправить', stop: 'Стоп', waiting: 'Ожидание ответа AI...', assist: 'Инструменты Assist', noActiveTitle: 'Нет активного документа.', openDocTools: 'Откройте CSV, JSON, Markdown или Mermaid вкладку, чтобы увидеть локальные и AI-инструменты.',
    mcpServers: 'MCP-серверы', mcpSubtitle: 'Включите сервер, затем откройте Tools или Resources. Вызовы tools всегда требуют разрешения.', desktopOnly: 'MCP доступен только в desktop-приложении.', desktopOnlyBody: 'Откройте Electron-приложение для подключения локальных MCP-серверов.', noMcp: 'MCP-серверы не настроены.', addImport: 'Добавьте сервер или импортируйте MCP-конфигурацию.', refresh: 'Обновить', add: 'Добавить', edit: 'Изменить', export: 'Экспорт', import: 'Импорт', enable: 'Включить', disable: 'Отключить', running: 'Работает', starting: 'Запуск', stopped: 'Остановлен',
  },
  it: {
    terminal: 'Terminale', terminalSubtitle: 'Shell integrata, Runner e assistenti IA', newTerminal: 'Nuovo terminale', chooseShell: 'Scegli un profilo shell', noTerminal: 'Nessun terminale in esecuzione', startApproved: 'Fai clic su + o scegli un profilo shell per avviare nel workspace approvato.', terminalWindow: 'Terminale OrPAD', loadingWorkspace: 'Caricamento workspace...', dockMain: 'Aggancia alla finestra principale', noWorkspace: 'Nessun workspace approvato',
    aiReady: 'La barra laterale IA è pronta.', aiReadyDoc: 'L’IA è pronta per {name}', aiDocPrompt: 'Chiedi una riscrittura, spiegazione o trasformazione usando il documento corrente come contesto.', aiGeneralPrompt: 'Fai una domanda generale o apri un documento per allegare contesto.', noActive: 'Nessun documento attivo. La chat funziona comunque; apri un file per allegare il contesto.', providerSettings: 'Impostazioni AI Provider', newChat: 'Nuova chat', rename: 'Rinomina', search: 'Cerca', send: 'Invia', stop: 'Ferma', waiting: 'In attesa della risposta IA...', assist: 'Strumenti Assist', noActiveTitle: 'Nessun documento attivo.', openDocTools: 'Apri una scheda CSV, JSON, Markdown o Mermaid per vedere strumenti locali e IA.',
    mcpServers: 'Server MCP', mcpSubtitle: 'Abilita un server, poi apri Tools o Resources. Le chiamate agli strumenti richiedono sempre permesso.', desktopOnly: 'MCP è disponibile solo su desktop.', desktopOnlyBody: 'Apri l’app Electron per collegare server MCP locali.', noMcp: 'Nessun server MCP configurato.', addImport: 'Aggiungi un server o importa una configurazione MCP per iniziare.', refresh: 'Aggiorna', add: 'Aggiungi', edit: 'Modifica', export: 'Esporta', import: 'Importa', enable: 'Abilita', disable: 'Disabilita', running: 'In esecuzione', starting: 'Avvio', stopped: 'Fermo',
  },
  ar: {
    terminal: 'الطرفية', terminalSubtitle: 'Shell مدمج وRunner ومساعدو AI', newTerminal: 'طرفية جديدة', chooseShell: 'اختر ملف Shell', noTerminal: 'لا توجد طرفية قيد التشغيل', startApproved: 'انقر + أو اختر ملف Shell للبدء داخل مساحة العمل المعتمدة.', terminalWindow: 'طرفية OrPAD', loadingWorkspace: 'جار تحميل مساحة العمل...', dockMain: 'إرساء في النافذة الرئيسية', noWorkspace: 'لا توجد مساحة عمل معتمدة بعد',
    aiReady: 'الشريط الجانبي AI جاهز.', aiReadyDoc: 'AI جاهز لـ {name}', aiDocPrompt: 'اطلب إعادة صياغة أو شرحا أو تحويل تنسيق باستخدام المستند الحالي كسياق.', aiGeneralPrompt: 'اطرح سؤالا عاما أو افتح مستندا لإرفاق سياق الملف.', noActive: 'لا يوجد مستند نشط. ما زال Chat يعمل؛ افتح ملفا لإرفاق سياق المستند.', providerSettings: 'إعدادات AI Provider', newChat: 'Chat جديد', rename: 'إعادة تسمية', search: 'بحث', send: 'إرسال', stop: 'إيقاف', waiting: 'بانتظار رد AI...', assist: 'أدوات Assist', noActiveTitle: 'لا يوجد مستند نشط.', openDocTools: 'افتح تبويب CSV أو JSON أو Markdown أو Mermaid لرؤية أدوات محلية وأدوات AI.',
    mcpServers: 'خوادم MCP', mcpSubtitle: 'فعّل خادما ثم افتح Tools أو Resources. استدعاءات الأدوات تتطلب إذنا دائما.', desktopOnly: 'MCP متاح على سطح المكتب فقط.', desktopOnlyBody: 'افتح تطبيق Electron للاتصال بخوادم MCP المحلية.', noMcp: 'لا توجد خوادم MCP مهيأة.', addImport: 'أضف خادما أو استورد إعداد MCP للبدء.', refresh: 'تحديث', add: 'إضافة', edit: 'تعديل', export: 'تصدير', import: 'استيراد', enable: 'تفعيل', disable: 'تعطيل', running: 'قيد التشغيل', starting: 'جار البدء', stopped: 'متوقف',
  },
  hi: {
    terminal: 'टर्मिनल', terminalSubtitle: 'एकीकृत Shell, Runner और AI सहायक', newTerminal: 'नया टर्मिनल', chooseShell: 'Shell प्रोफाइल चुनें', noTerminal: 'कोई टर्मिनल चालू नहीं है', startApproved: '+ क्लिक करें या स्वीकृत workspace में शुरू करने के लिए Shell प्रोफाइल चुनें।', terminalWindow: 'OrPAD टर्मिनल', loadingWorkspace: 'Workspace लोड हो रहा है...', dockMain: 'मुख्य विंडो में डॉक करें', noWorkspace: 'अभी कोई स्वीकृत workspace नहीं है',
    aiReady: 'AI साइडबार तैयार है।', aiReadyDoc: 'AI {name} के लिए तैयार है', aiDocPrompt: 'वर्तमान दस्तावेज को संदर्भ बनाकर rewrite, explanation या format transform मांगें।', aiGeneralPrompt: 'सामान्य प्रश्न पूछें या file context जोड़ने के लिए दस्तावेज खोलें।', noActive: 'कोई सक्रिय दस्तावेज नहीं है। Chat अभी भी काम करता है; context जोड़ने के लिए file खोलें।', providerSettings: 'AI Provider सेटिंग्स', newChat: 'नया Chat', rename: 'नाम बदलें', search: 'खोजें', send: 'भेजें', stop: 'रोकें', waiting: 'AI response की प्रतीक्षा...', assist: 'Assist tools', noActiveTitle: 'कोई सक्रिय दस्तावेज नहीं है।', openDocTools: 'local और AI tools देखने के लिए CSV, JSON, Markdown या Mermaid tab खोलें।',
    mcpServers: 'MCP सर्वर', mcpSubtitle: 'Server enable करें, फिर Tools या Resources खोलें। Tool calls हमेशा permission मांगते हैं।', desktopOnly: 'MCP केवल desktop पर उपलब्ध है।', desktopOnlyBody: 'Local MCP servers से जुड़ने के लिए Electron app खोलें।', noMcp: 'कोई MCP server configured नहीं है।', addImport: 'शुरू करने के लिए server जोड़ें या MCP config import करें।', refresh: 'Refresh', add: 'Add', edit: 'Edit', export: 'Export', import: 'Import', enable: 'Enable', disable: 'Disable', running: 'Running', starting: 'Starting', stopped: 'Stopped',
  },
  nl: {
    terminal: 'Terminal', terminalSubtitle: 'Geïntegreerde shell, Runner en AI-helpers', newTerminal: 'Nieuwe terminal', chooseShell: 'Kies een shellprofiel', noTerminal: 'Geen terminal actief', startApproved: 'Klik op + of kies een shellprofiel om te starten in de goedgekeurde workspace.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Workspace laden...', dockMain: 'Dock aan hoofdvenster', noWorkspace: 'Nog geen goedgekeurde workspace',
    aiReady: 'De AI-zijbalk is klaar.', aiReadyDoc: 'AI is klaar voor {name}', aiDocPrompt: 'Vraag om herschrijven, uitleg of formaatconversie met het huidige document als context.', aiGeneralPrompt: 'Stel een algemene vraag of open een document om context toe te voegen.', noActive: 'Geen actief document. Chat werkt nog steeds; open een bestand om documentcontext toe te voegen.', providerSettings: 'AI Provider-instellingen', newChat: 'Nieuwe chat', rename: 'Naam wijzigen', search: 'Zoeken', send: 'Verzenden', stop: 'Stoppen', waiting: 'Wachten op AI-antwoord...', assist: 'Assist-tools', noActiveTitle: 'Geen actief document.', openDocTools: 'Open een CSV-, JSON-, Markdown- of Mermaid-tab om lokale en AI-tools te zien.',
    mcpServers: 'MCP-servers', mcpSubtitle: 'Schakel een server in en open daarna Tools of Resources. Tool calls vragen altijd toestemming.', desktopOnly: 'MCP is alleen beschikbaar in de desktopapp.', desktopOnlyBody: 'Open de Electron-app om lokale MCP-servers te verbinden.', noMcp: 'Geen MCP-servers geconfigureerd.', addImport: 'Voeg een server toe of importeer een MCP-configuratie.', refresh: 'Vernieuwen', add: 'Toevoegen', edit: 'Bewerken', export: 'Exporteren', import: 'Importeren', enable: 'Inschakelen', disable: 'Uitschakelen', running: 'Actief', starting: 'Starten', stopped: 'Gestopt',
  },
  pl: {
    terminal: 'Terminal', terminalSubtitle: 'Zintegrowana shell, Runner i pomocnicy AI', newTerminal: 'Nowy terminal', chooseShell: 'Wybierz profil shell', noTerminal: 'Brak uruchomionego terminala', startApproved: 'Kliknij + lub wybierz profil shell, aby uruchomić w zatwierdzonym workspace.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Ładowanie workspace...', dockMain: 'Zadokuj w głównym oknie', noWorkspace: 'Brak zatwierdzonego workspace',
    aiReady: 'Panel boczny AI jest gotowy.', aiReadyDoc: 'AI jest gotowe dla {name}', aiDocPrompt: 'Poproś o przeredagowanie, wyjaśnienie lub zmianę formatu, używając bieżącego dokumentu jako kontekstu.', aiGeneralPrompt: 'Zadaj ogólne pytanie albo otwórz dokument, aby dodać kontekst pliku.', noActive: 'Brak aktywnego dokumentu. Chat nadal działa; otwórz plik, aby dodać kontekst dokumentu.', providerSettings: 'Ustawienia AI Provider', newChat: 'Nowy chat', rename: 'Zmień nazwę', search: 'Szukaj', send: 'Wyślij', stop: 'Stop', waiting: 'Oczekiwanie na odpowiedź AI...', assist: 'Narzędzia Assist', noActiveTitle: 'Brak aktywnego dokumentu.', openDocTools: 'Otwórz kartę CSV, JSON, Markdown lub Mermaid, aby zobaczyć narzędzia lokalne i AI.',
    mcpServers: 'Serwery MCP', mcpSubtitle: 'Włącz serwer, a potem otwórz Tools lub Resources. Wywołania narzędzi zawsze wymagają zgody.', desktopOnly: 'MCP jest dostępne tylko w aplikacji desktop.', desktopOnlyBody: 'Otwórz aplikację Electron, aby połączyć lokalne serwery MCP.', noMcp: 'Brak skonfigurowanych serwerów MCP.', addImport: 'Dodaj serwer lub zaimportuj konfigurację MCP.', refresh: 'Odśwież', add: 'Dodaj', edit: 'Edytuj', export: 'Eksport', import: 'Import', enable: 'Włącz', disable: 'Wyłącz', running: 'Działa', starting: 'Uruchamianie', stopped: 'Zatrzymany',
  },
  tr: {
    terminal: 'Terminal', terminalSubtitle: 'Entegre Shell, Runner ve AI yardımcıları', newTerminal: 'Yeni terminal', chooseShell: 'Shell profili seç', noTerminal: 'Çalışan terminal yok', startApproved: 'Onaylı workspace içinde başlatmak için + düğmesine tıklayın veya Shell profili seçin.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Workspace yükleniyor...', dockMain: 'Ana pencereye yerleştir', noWorkspace: 'Henüz onaylı workspace yok',
    aiReady: 'AI kenar çubuğu hazır.', aiReadyDoc: 'AI {name} için hazır', aiDocPrompt: 'Geçerli belgeyi bağlam olarak kullanarak yeniden yazma, açıklama veya format dönüşümü isteyin.', aiGeneralPrompt: 'Genel bir soru sorun veya dosya bağlamı eklemek için belge açın.', noActive: 'Etkin belge yok. Chat yine de çalışır; belge bağlamı eklemek için dosya açın.', providerSettings: 'AI Provider ayarları', newChat: 'Yeni Chat', rename: 'Yeniden adlandır', search: 'Ara', send: 'Gönder', stop: 'Durdur', waiting: 'AI yanıtı bekleniyor...', assist: 'Assist araçları', noActiveTitle: 'Etkin belge yok.', openDocTools: 'Yerel ve AI araçlarını görmek için CSV, JSON, Markdown veya Mermaid sekmesi açın.',
    mcpServers: 'MCP sunucuları', mcpSubtitle: 'Bir sunucuyu etkinleştirin, ardından Tools veya Resources açın. Tool çağrıları her zaman izin ister.', desktopOnly: 'MCP yalnızca desktop uygulamasında kullanılabilir.', desktopOnlyBody: 'Yerel MCP sunucularına bağlanmak için Electron uygulamasını açın.', noMcp: 'Yapılandırılmış MCP sunucusu yok.', addImport: 'Başlamak için sunucu ekleyin veya MCP config import edin.', refresh: 'Yenile', add: 'Ekle', edit: 'Düzenle', export: 'Dışa aktar', import: 'İçe aktar', enable: 'Etkinleştir', disable: 'Devre dışı bırak', running: 'Çalışıyor', starting: 'Başlatılıyor', stopped: 'Durduruldu',
  },
  vi: {
    terminal: 'Terminal', terminalSubtitle: 'Shell tích hợp, Runner và trợ lý AI', newTerminal: 'Terminal mới', chooseShell: 'Chọn hồ sơ Shell', noTerminal: 'Không có terminal đang chạy', startApproved: 'Bấm + hoặc chọn hồ sơ Shell để bắt đầu trong workspace đã được duyệt.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Đang tải workspace...', dockMain: 'Gắn vào cửa sổ chính', noWorkspace: 'Chưa có workspace được duyệt',
    aiReady: 'Thanh bên AI đã sẵn sàng.', aiReadyDoc: 'AI đã sẵn sàng cho {name}', aiDocPrompt: 'Yêu cầu viết lại, giải thích hoặc chuyển đổi định dạng bằng tài liệu hiện tại làm ngữ cảnh.', aiGeneralPrompt: 'Đặt câu hỏi chung hoặc mở tài liệu để đính kèm ngữ cảnh file.', noActive: 'Không có tài liệu đang hoạt động. Chat vẫn dùng được; mở file để đính kèm ngữ cảnh.', providerSettings: 'Cài đặt AI Provider', newChat: 'Chat mới', rename: 'Đổi tên', search: 'Tìm kiếm', send: 'Gửi', stop: 'Dừng', waiting: 'Đang chờ phản hồi AI...', assist: 'Công cụ Assist', noActiveTitle: 'Không có tài liệu đang hoạt động.', openDocTools: 'Mở tab CSV, JSON, Markdown hoặc Mermaid để xem công cụ local và AI.',
    mcpServers: 'Máy chủ MCP', mcpSubtitle: 'Bật máy chủ rồi mở Tools hoặc Resources. Tool calls luôn cần quyền.', desktopOnly: 'MCP chỉ dùng trên desktop.', desktopOnlyBody: 'Mở ứng dụng Electron để kết nối máy chủ MCP cục bộ.', noMcp: 'Chưa cấu hình máy chủ MCP.', addImport: 'Thêm máy chủ hoặc import cấu hình MCP để bắt đầu.', refresh: 'Làm mới', add: 'Thêm', edit: 'Sửa', export: 'Xuất', import: 'Nhập', enable: 'Bật', disable: 'Tắt', running: 'Đang chạy', starting: 'Đang khởi động', stopped: 'Đã dừng',
  },
  th: {
    terminal: 'เทอร์มินัล', terminalSubtitle: 'Shell รวม, Runner และผู้ช่วย AI', newTerminal: 'เทอร์มินัลใหม่', chooseShell: 'เลือกโปรไฟล์ Shell', noTerminal: 'ไม่มีเทอร์มินัลที่กำลังทำงาน', startApproved: 'คลิก + หรือเลือกโปรไฟล์ Shell เพื่อเริ่มใน workspace ที่อนุมัติแล้ว', terminalWindow: 'เทอร์มินัล OrPAD', loadingWorkspace: 'กำลังโหลด workspace...', dockMain: 'Dock ไปยังหน้าต่างหลัก', noWorkspace: 'ยังไม่มี workspace ที่อนุมัติ',
    aiReady: 'แถบด้านข้าง AI พร้อมแล้ว', aiReadyDoc: 'AI พร้อมสำหรับ {name}', aiDocPrompt: 'ขอให้เขียนใหม่ อธิบาย หรือแปลงรูปแบบโดยใช้เอกสารปัจจุบันเป็นบริบท', aiGeneralPrompt: 'ถามคำถามทั่วไป หรือเปิดเอกสารเพื่อแนบบริบทไฟล์', noActive: 'ไม่มีเอกสารที่ใช้งานอยู่ Chat ยังใช้ได้ เปิดไฟล์เพื่อแนบบริบทเอกสาร', providerSettings: 'การตั้งค่า AI Provider', newChat: 'Chat ใหม่', rename: 'เปลี่ยนชื่อ', search: 'ค้นหา', send: 'ส่ง', stop: 'หยุด', waiting: 'กำลังรอคำตอบจาก AI...', assist: 'เครื่องมือ Assist', noActiveTitle: 'ไม่มีเอกสารที่ใช้งานอยู่', openDocTools: 'เปิดแท็บ CSV, JSON, Markdown หรือ Mermaid เพื่อดูเครื่องมือ local และ AI',
    mcpServers: 'เซิร์ฟเวอร์ MCP', mcpSubtitle: 'เปิดใช้เซิร์ฟเวอร์ แล้วเปิด Tools หรือ Resources การเรียก tool ต้องขออนุญาตเสมอ', desktopOnly: 'MCP ใช้ได้เฉพาะ desktop', desktopOnlyBody: 'เปิดแอป Electron เพื่อเชื่อมต่อเซิร์ฟเวอร์ MCP ในเครื่อง', noMcp: 'ยังไม่มีเซิร์ฟเวอร์ MCP ที่ตั้งค่าไว้', addImport: 'เพิ่มเซิร์ฟเวอร์หรือนำเข้า MCP config เพื่อเริ่มต้น', refresh: 'รีเฟรช', add: 'เพิ่ม', edit: 'แก้ไข', export: 'ส่งออก', import: 'นำเข้า', enable: 'เปิดใช้', disable: 'ปิดใช้', running: 'กำลังทำงาน', starting: 'กำลังเริ่ม', stopped: 'หยุดแล้ว',
  },
  sv: {
    terminal: 'Terminal', terminalSubtitle: 'Integrerat shell, Runner och AI-hjälpare', newTerminal: 'Ny terminal', chooseShell: 'Välj shellprofil', noTerminal: 'Ingen terminal körs', startApproved: 'Klicka på + eller välj en shellprofil för att starta i godkänd workspace.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Läser in workspace...', dockMain: 'Docka till huvudfönster', noWorkspace: 'Ingen godkänd workspace ännu',
    aiReady: 'AI-sidopanelen är redo.', aiReadyDoc: 'AI är redo för {name}', aiDocPrompt: 'Be om omskrivning, förklaring eller formatomvandling med aktuellt dokument som kontext.', aiGeneralPrompt: 'Ställ en allmän fråga eller öppna ett dokument för att lägga till filkontext.', noActive: 'Inget aktivt dokument. Chat fungerar ändå; öppna en fil för att lägga till dokumentkontext.', providerSettings: 'AI Provider-inställningar', newChat: 'Ny Chat', rename: 'Byt namn', search: 'Sök', send: 'Skicka', stop: 'Stoppa', waiting: 'Väntar på AI-svar...', assist: 'Assist-verktyg', noActiveTitle: 'Inget aktivt dokument.', openDocTools: 'Öppna en CSV-, JSON-, Markdown- eller Mermaid-flik för lokala och AI-verktyg.',
    mcpServers: 'MCP-servrar', mcpSubtitle: 'Aktivera en server och öppna sedan Tools eller Resources. Tool calls kräver alltid behörighet.', desktopOnly: 'MCP är endast för desktop.', desktopOnlyBody: 'Öppna Electron-appen för att ansluta lokala MCP-servrar.', noMcp: 'Inga MCP-servrar konfigurerade.', addImport: 'Lägg till en server eller importera MCP-konfiguration.', refresh: 'Uppdatera', add: 'Lägg till', edit: 'Redigera', export: 'Exportera', import: 'Importera', enable: 'Aktivera', disable: 'Inaktivera', running: 'Körs', starting: 'Startar', stopped: 'Stoppad',
  },
  da: {
    terminal: 'Terminal', terminalSubtitle: 'Integreret shell, Runner og AI-hjælpere', newTerminal: 'Ny terminal', chooseShell: 'Vælg shellprofil', noTerminal: 'Ingen terminal kører', startApproved: 'Klik + eller vælg en shellprofil for at starte i godkendt workspace.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Indlæser workspace...', dockMain: 'Dock til hovedvindue', noWorkspace: 'Ingen godkendt workspace endnu',
    aiReady: 'AI-sidepanelet er klar.', aiReadyDoc: 'AI er klar til {name}', aiDocPrompt: 'Bed om omskrivning, forklaring eller formatkonvertering med det aktuelle dokument som kontekst.', aiGeneralPrompt: 'Stil et generelt spørgsmål eller åbn et dokument for at vedhæfte filkontekst.', noActive: 'Intet aktivt dokument. Chat virker stadig; åbn en fil for at tilføje dokumentkontekst.', providerSettings: 'AI Provider-indstillinger', newChat: 'Ny Chat', rename: 'Omdøb', search: 'Søg', send: 'Send', stop: 'Stop', waiting: 'Venter på AI-svar...', assist: 'Assist-værktøjer', noActiveTitle: 'Intet aktivt dokument.', openDocTools: 'Åbn en CSV-, JSON-, Markdown- eller Mermaid-fane for lokale og AI-værktøjer.',
    mcpServers: 'MCP-servere', mcpSubtitle: 'Aktivér en server, og åbn derefter Tools eller Resources. Tool calls kræver altid tilladelse.', desktopOnly: 'MCP er kun til desktop.', desktopOnlyBody: 'Åbn Electron-appen for at forbinde lokale MCP-servere.', noMcp: 'Ingen MCP-servere konfigureret.', addImport: 'Tilføj en server eller importer MCP-konfiguration.', refresh: 'Opdater', add: 'Tilføj', edit: 'Rediger', export: 'Eksporter', import: 'Importer', enable: 'Aktivér', disable: 'Deaktivér', running: 'Kører', starting: 'Starter', stopped: 'Stoppet',
  },
  fi: {
    terminal: 'Pääte', terminalSubtitle: 'Integroitu shell, Runner ja AI-avustajat', newTerminal: 'Uusi pääte', chooseShell: 'Valitse shell-profiili', noTerminal: 'Päätettä ei ole käynnissä', startApproved: 'Napsauta + tai valitse shell-profiili käynnistääksesi hyväksytyssä workspacessa.', terminalWindow: 'OrPAD-pääte', loadingWorkspace: 'Ladataan workspacea...', dockMain: 'Telakoi pääikkunaan', noWorkspace: 'Hyväksyttyä workspacea ei vielä ole',
    aiReady: 'AI-sivupalkki on valmis.', aiReadyDoc: 'AI on valmis kohteelle {name}', aiDocPrompt: 'Pyydä uudelleenkirjoitusta, selitystä tai formaattimuunnosta käyttäen nykyistä dokumenttia kontekstina.', aiGeneralPrompt: 'Kysy yleinen kysymys tai avaa dokumentti lisätäksesi tiedostokontekstin.', noActive: 'Aktiivista dokumenttia ei ole. Chat toimii silti; avaa tiedosto lisätäksesi kontekstin.', providerSettings: 'AI Provider -asetukset', newChat: 'Uusi Chat', rename: 'Nimeä uudelleen', search: 'Haku', send: 'Lähetä', stop: 'Pysäytä', waiting: 'Odotetaan AI-vastausta...', assist: 'Assist-työkalut', noActiveTitle: 'Aktiivista dokumenttia ei ole.', openDocTools: 'Avaa CSV-, JSON-, Markdown- tai Mermaid-välilehti nähdäksesi paikalliset ja AI-työkalut.',
    mcpServers: 'MCP-palvelimet', mcpSubtitle: 'Ota palvelin käyttöön ja avaa sitten Tools tai Resources. Tool calls vaatii aina luvan.', desktopOnly: 'MCP on vain desktopissa.', desktopOnlyBody: 'Avaa Electron-sovellus yhdistääksesi paikalliset MCP-palvelimet.', noMcp: 'MCP-palvelimia ei ole määritetty.', addImport: 'Lisää palvelin tai tuo MCP-määritys aloittaaksesi.', refresh: 'Päivitä', add: 'Lisää', edit: 'Muokkaa', export: 'Vie', import: 'Tuo', enable: 'Ota käyttöön', disable: 'Poista käytöstä', running: 'Käynnissä', starting: 'Käynnistyy', stopped: 'Pysäytetty',
  },
  nb: {
    terminal: 'Terminal', terminalSubtitle: 'Integrert shell, Runner og AI-hjelpere', newTerminal: 'Ny terminal', chooseShell: 'Velg shellprofil', noTerminal: 'Ingen terminal kjører', startApproved: 'Klikk + eller velg en shellprofil for å starte i godkjent workspace.', terminalWindow: 'OrPAD Terminal', loadingWorkspace: 'Laster workspace...', dockMain: 'Dock til hovedvindu', noWorkspace: 'Ingen godkjent workspace ennå',
    aiReady: 'AI-sidepanelet er klart.', aiReadyDoc: 'AI er klar for {name}', aiDocPrompt: 'Be om omskriving, forklaring eller formatkonvertering med gjeldende dokument som kontekst.', aiGeneralPrompt: 'Still et generelt spørsmål eller åpne et dokument for å legge ved filkontekst.', noActive: 'Ingen aktivt dokument. Chat fungerer fortsatt; åpne en fil for å legge til dokumentkontekst.', providerSettings: 'AI Provider-innstillinger', newChat: 'Ny Chat', rename: 'Gi nytt navn', search: 'Søk', send: 'Send', stop: 'Stopp', waiting: 'Venter på AI-svar...', assist: 'Assist-verktøy', noActiveTitle: 'Ingen aktivt dokument.', openDocTools: 'Åpne en CSV-, JSON-, Markdown- eller Mermaid-fane for lokale og AI-verktøy.',
    mcpServers: 'MCP-servere', mcpSubtitle: 'Aktiver en server, og åpne deretter Tools eller Resources. Tool calls krever alltid tillatelse.', desktopOnly: 'MCP er bare for desktop.', desktopOnlyBody: 'Åpne Electron-appen for å koble til lokale MCP-servere.', noMcp: 'Ingen MCP-servere konfigurert.', addImport: 'Legg til en server eller importer MCP-konfigurasjon.', refresh: 'Oppdater', add: 'Legg til', edit: 'Rediger', export: 'Eksporter', import: 'Importer', enable: 'Aktiver', disable: 'Deaktiver', running: 'Kjører', starting: 'Starter', stopped: 'Stoppet',
  },
  cs: {
    terminal: 'Terminál', terminalSubtitle: 'Integrovaný shell, Runner a AI asistenti', newTerminal: 'Nový terminál', chooseShell: 'Vyberte profil shellu', noTerminal: 'Neběží žádný terminál', startApproved: 'Klikněte na + nebo vyberte profil shellu pro spuštění ve schváleném workspace.', terminalWindow: 'Terminál OrPAD', loadingWorkspace: 'Načítání workspace...', dockMain: 'Ukotvit do hlavního okna', noWorkspace: 'Zatím žádný schválený workspace',
    aiReady: 'Postranní panel AI je připraven.', aiReadyDoc: 'AI je připravena pro {name}', aiDocPrompt: 'Požádejte o přepsání, vysvětlení nebo změnu formátu s aktuálním dokumentem jako kontextem.', aiGeneralPrompt: 'Položte obecnou otázku nebo otevřete dokument pro přidání kontextu.', noActive: 'Žádný aktivní dokument. Chat stále funguje; otevřete soubor pro přidání kontextu dokumentu.', providerSettings: 'Nastavení AI Provider', newChat: 'Nový Chat', rename: 'Přejmenovat', search: 'Hledat', send: 'Odeslat', stop: 'Stop', waiting: 'Čekání na odpověď AI...', assist: 'Nástroje Assist', noActiveTitle: 'Žádný aktivní dokument.', openDocTools: 'Otevřete kartu CSV, JSON, Markdown nebo Mermaid pro lokální a AI nástroje.',
    mcpServers: 'MCP servery', mcpSubtitle: 'Povolte server a poté otevřete Tools nebo Resources. Tool calls vždy vyžadují oprávnění.', desktopOnly: 'MCP je dostupné jen v desktopu.', desktopOnlyBody: 'Otevřete aplikaci Electron pro připojení lokálních MCP serverů.', noMcp: 'Nejsou nakonfigurovány žádné MCP servery.', addImport: 'Přidejte server nebo importujte MCP konfiguraci.', refresh: 'Obnovit', add: 'Přidat', edit: 'Upravit', export: 'Export', import: 'Import', enable: 'Povolit', disable: 'Zakázat', running: 'Běží', starting: 'Spouštění', stopped: 'Zastaveno',
  },
  el: {
    terminal: 'Τερματικό', terminalSubtitle: 'Ενσωματωμένο Shell, Runner και βοηθοί AI', newTerminal: 'Νέο τερματικό', chooseShell: 'Επιλέξτε προφίλ Shell', noTerminal: 'Δεν εκτελείται τερματικό', startApproved: 'Κάντε κλικ στο + ή επιλέξτε προφίλ Shell για εκκίνηση στο εγκεκριμένο workspace.', terminalWindow: 'Τερματικό OrPAD', loadingWorkspace: 'Φόρτωση workspace...', dockMain: 'Προσάρτηση στο κύριο παράθυρο', noWorkspace: 'Δεν υπάρχει ακόμη εγκεκριμένο workspace',
    aiReady: 'Η πλαϊνή μπάρα AI είναι έτοιμη.', aiReadyDoc: 'Το AI είναι έτοιμο για {name}', aiDocPrompt: 'Ζητήστε αναδιατύπωση, εξήγηση ή μετατροπή μορφής με το τρέχον έγγραφο ως context.', aiGeneralPrompt: 'Κάντε μια γενική ερώτηση ή ανοίξτε έγγραφο για προσθήκη context.', noActive: 'Δεν υπάρχει ενεργό έγγραφο. Το Chat λειτουργεί ακόμα· ανοίξτε αρχείο για προσθήκη context.', providerSettings: 'Ρυθμίσεις AI Provider', newChat: 'Νέο Chat', rename: 'Μετονομασία', search: 'Αναζήτηση', send: 'Αποστολή', stop: 'Διακοπή', waiting: 'Αναμονή απάντησης AI...', assist: 'Εργαλεία Assist', noActiveTitle: 'Δεν υπάρχει ενεργό έγγραφο.', openDocTools: 'Ανοίξτε καρτέλα CSV, JSON, Markdown ή Mermaid για τοπικά και AI εργαλεία.',
    mcpServers: 'Διακομιστές MCP', mcpSubtitle: 'Ενεργοποιήστε server και ανοίξτε Tools ή Resources. Τα tool calls απαιτούν πάντα άδεια.', desktopOnly: 'Το MCP είναι μόνο για desktop.', desktopOnlyBody: 'Ανοίξτε την εφαρμογή Electron για σύνδεση τοπικών MCP servers.', noMcp: 'Δεν έχουν ρυθμιστεί MCP servers.', addImport: 'Προσθέστε server ή εισαγάγετε MCP config.', refresh: 'Ανανέωση', add: 'Προσθήκη', edit: 'Επεξεργασία', export: 'Εξαγωγή', import: 'Εισαγωγή', enable: 'Ενεργοποίηση', disable: 'Απενεργοποίηση', running: 'Εκτελείται', starting: 'Εκκίνηση', stopped: 'Σταματημένο',
  },
  hu: {
    terminal: 'Terminál', terminalSubtitle: 'Integrált shell, Runner és AI-segédek', newTerminal: 'Új terminál', chooseShell: 'Shell-profil kiválasztása', noTerminal: 'Nem fut terminál', startApproved: 'Kattints a + gombra vagy válassz shell-profilt az engedélyezett workspace-ben indításhoz.', terminalWindow: 'OrPAD Terminál', loadingWorkspace: 'Workspace betöltése...', dockMain: 'Dokkolás a főablakba', noWorkspace: 'Még nincs engedélyezett workspace',
    aiReady: 'Az AI oldalsáv készen áll.', aiReadyDoc: 'Az AI készen áll ehhez: {name}', aiDocPrompt: 'Kérj átírást, magyarázatot vagy formátumváltást az aktuális dokumentummal kontextusként.', aiGeneralPrompt: 'Tegyél fel általános kérdést, vagy nyiss meg dokumentumot fájlkontekstus hozzáadásához.', noActive: 'Nincs aktív dokumentum. A Chat továbbra is működik; nyiss meg fájlt a kontextushoz.', providerSettings: 'AI Provider beállítások', newChat: 'Új Chat', rename: 'Átnevezés', search: 'Keresés', send: 'Küldés', stop: 'Stop', waiting: 'Várakozás AI-válaszra...', assist: 'Assist eszközök', noActiveTitle: 'Nincs aktív dokumentum.', openDocTools: 'Nyiss meg CSV, JSON, Markdown vagy Mermaid fület a helyi és AI eszközökhöz.',
    mcpServers: 'MCP szerverek', mcpSubtitle: 'Engedélyezz egy szervert, majd nyisd meg a Tools vagy Resources részt. A tool calls mindig engedélyt kér.', desktopOnly: 'Az MCP csak desktopon érhető el.', desktopOnlyBody: 'Nyisd meg az Electron appot a helyi MCP szerverekhez.', noMcp: 'Nincs beállított MCP szerver.', addImport: 'Adj hozzá szervert vagy importálj MCP konfigurációt.', refresh: 'Frissítés', add: 'Hozzáadás', edit: 'Szerkesztés', export: 'Export', import: 'Import', enable: 'Engedélyezés', disable: 'Letiltás', running: 'Fut', starting: 'Indul', stopped: 'Leállítva',
  },
  ro: {
    terminal: 'Terminal', terminalSubtitle: 'Shell integrat, Runner și asistenți AI', newTerminal: 'Terminal nou', chooseShell: 'Alege un profil shell', noTerminal: 'Nu rulează niciun terminal', startApproved: 'Apasă + sau alege un profil shell pentru a porni în workspace-ul aprobat.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Se încarcă workspace-ul...', dockMain: 'Andochează în fereastra principală', noWorkspace: 'Niciun workspace aprobat încă',
    aiReady: 'Bara laterală AI este gata.', aiReadyDoc: 'AI este gata pentru {name}', aiDocPrompt: 'Cere rescriere, explicație sau transformare de format folosind documentul curent ca context.', aiGeneralPrompt: 'Pune o întrebare generală sau deschide un document pentru context.', noActive: 'Niciun document activ. Chat funcționează în continuare; deschide un fișier pentru context.', providerSettings: 'Setări AI Provider', newChat: 'Chat nou', rename: 'Redenumește', search: 'Caută', send: 'Trimite', stop: 'Oprește', waiting: 'Se așteaptă răspunsul AI...', assist: 'Instrumente Assist', noActiveTitle: 'Niciun document activ.', openDocTools: 'Deschide un tab CSV, JSON, Markdown sau Mermaid pentru instrumente locale și AI.',
    mcpServers: 'Servere MCP', mcpSubtitle: 'Activează un server, apoi deschide Tools sau Resources. Tool calls cer întotdeauna permisiune.', desktopOnly: 'MCP este disponibil doar pe desktop.', desktopOnlyBody: 'Deschide aplicația Electron pentru servere MCP locale.', noMcp: 'Nu există servere MCP configurate.', addImport: 'Adaugă un server sau importă o configurație MCP.', refresh: 'Reîmprospătează', add: 'Adaugă', edit: 'Editează', export: 'Exportă', import: 'Importă', enable: 'Activează', disable: 'Dezactivează', running: 'Rulează', starting: 'Pornește', stopped: 'Oprit',
  },
  uk: {
    terminal: 'Термінал', terminalSubtitle: 'Вбудована shell, Runner і AI-помічники', newTerminal: 'Новий термінал', chooseShell: 'Виберіть профіль shell', noTerminal: 'Немає запущеного термінала', startApproved: 'Натисніть + або виберіть профіль shell для запуску в дозволеному workspace.', terminalWindow: 'Термінал OrPAD', loadingWorkspace: 'Завантаження workspace...', dockMain: 'Закріпити в головному вікні', noWorkspace: 'Дозволеного workspace ще немає',
    aiReady: 'Бічна панель AI готова.', aiReadyDoc: 'AI готовий для {name}', aiDocPrompt: 'Попросіть переписати, пояснити або змінити формат, використовуючи поточний документ як контекст.', aiGeneralPrompt: 'Поставте загальне питання або відкрийте документ, щоб додати контекст файлу.', noActive: 'Немає активного документа. Chat усе ще працює; відкрийте файл, щоб додати контекст.', providerSettings: 'Налаштування AI Provider', newChat: 'Новий Chat', rename: 'Перейменувати', search: 'Пошук', send: 'Надіслати', stop: 'Стоп', waiting: 'Очікування відповіді AI...', assist: 'Інструменти Assist', noActiveTitle: 'Немає активного документа.', openDocTools: 'Відкрийте вкладку CSV, JSON, Markdown або Mermaid, щоб побачити локальні й AI інструменти.',
    mcpServers: 'MCP-сервери', mcpSubtitle: 'Увімкніть сервер, потім відкрийте Tools або Resources. Tool calls завжди потребують дозволу.', desktopOnly: 'MCP доступний лише в desktop-додатку.', desktopOnlyBody: 'Відкрийте Electron-додаток для підключення локальних MCP-серверів.', noMcp: 'MCP-сервери не налаштовані.', addImport: 'Додайте сервер або імпортуйте MCP-конфігурацію.', refresh: 'Оновити', add: 'Додати', edit: 'Редагувати', export: 'Експорт', import: 'Імпорт', enable: 'Увімкнути', disable: 'Вимкнути', running: 'Працює', starting: 'Запуск', stopped: 'Зупинено',
  },
  id: {
    terminal: 'Terminal', terminalSubtitle: 'Shell terintegrasi, Runner, dan asisten AI', newTerminal: 'Terminal baru', chooseShell: 'Pilih profil Shell', noTerminal: 'Tidak ada terminal berjalan', startApproved: 'Klik + atau pilih profil Shell untuk memulai di workspace yang disetujui.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Memuat workspace...', dockMain: 'Dock ke jendela utama', noWorkspace: 'Belum ada workspace yang disetujui',
    aiReady: 'Sidebar AI siap.', aiReadyDoc: 'AI siap untuk {name}', aiDocPrompt: 'Minta rewrite, penjelasan, atau transformasi format dengan dokumen saat ini sebagai konteks.', aiGeneralPrompt: 'Ajukan pertanyaan umum atau buka dokumen untuk melampirkan konteks file.', noActive: 'Tidak ada dokumen aktif. Chat tetap berfungsi; buka file untuk melampirkan konteks.', providerSettings: 'Pengaturan AI Provider', newChat: 'Chat baru', rename: 'Ubah nama', search: 'Cari', send: 'Kirim', stop: 'Berhenti', waiting: 'Menunggu respons AI...', assist: 'Alat Assist', noActiveTitle: 'Tidak ada dokumen aktif.', openDocTools: 'Buka tab CSV, JSON, Markdown, atau Mermaid untuk melihat alat lokal dan AI.',
    mcpServers: 'Server MCP', mcpSubtitle: 'Aktifkan server, lalu buka Tools atau Resources. Tool calls selalu memerlukan izin.', desktopOnly: 'MCP hanya tersedia di desktop.', desktopOnlyBody: 'Buka aplikasi Electron untuk menghubungkan server MCP lokal.', noMcp: 'Belum ada server MCP yang dikonfigurasi.', addImport: 'Tambahkan server atau import konfigurasi MCP untuk mulai.', refresh: 'Refresh', add: 'Tambah', edit: 'Edit', export: 'Ekspor', import: 'Impor', enable: 'Aktifkan', disable: 'Nonaktifkan', running: 'Berjalan', starting: 'Memulai', stopped: 'Berhenti',
  },
  ms: {
    terminal: 'Terminal', terminalSubtitle: 'Shell bersepadu, Runner dan pembantu AI', newTerminal: 'Terminal baharu', chooseShell: 'Pilih profil Shell', noTerminal: 'Tiada terminal berjalan', startApproved: 'Klik + atau pilih profil Shell untuk bermula dalam workspace yang diluluskan.', terminalWindow: 'Terminal OrPAD', loadingWorkspace: 'Memuatkan workspace...', dockMain: 'Dock ke tetingkap utama', noWorkspace: 'Belum ada workspace diluluskan',
    aiReady: 'Sidebar AI sudah sedia.', aiReadyDoc: 'AI sedia untuk {name}', aiDocPrompt: 'Minta tulis semula, penjelasan atau transformasi format menggunakan dokumen semasa sebagai konteks.', aiGeneralPrompt: 'Tanya soalan umum atau buka dokumen untuk melampirkan konteks fail.', noActive: 'Tiada dokumen aktif. Chat masih berfungsi; buka fail untuk melampirkan konteks.', providerSettings: 'Tetapan AI Provider', newChat: 'Chat baharu', rename: 'Namakan semula', search: 'Cari', send: 'Hantar', stop: 'Berhenti', waiting: 'Menunggu respons AI...', assist: 'Alat Assist', noActiveTitle: 'Tiada dokumen aktif.', openDocTools: 'Buka tab CSV, JSON, Markdown atau Mermaid untuk melihat alat tempatan dan AI.',
    mcpServers: 'Pelayan MCP', mcpSubtitle: 'Aktifkan pelayan, kemudian buka Tools atau Resources. Tool calls sentiasa memerlukan izin.', desktopOnly: 'MCP hanya tersedia di desktop.', desktopOnlyBody: 'Buka aplikasi Electron untuk menyambung pelayan MCP setempat.', noMcp: 'Tiada pelayan MCP dikonfigurasi.', addImport: 'Tambah pelayan atau import konfigurasi MCP untuk bermula.', refresh: 'Segar semula', add: 'Tambah', edit: 'Edit', export: 'Eksport', import: 'Import', enable: 'Aktifkan', disable: 'Nyahaktif', running: 'Berjalan', starting: 'Memulakan', stopped: 'Berhenti',
  },
  he: {
    terminal: 'מסוף', terminalSubtitle: 'Shell משולב, Runner ועוזרי AI', newTerminal: 'מסוף חדש', chooseShell: 'בחר פרופיל Shell', noTerminal: 'אין מסוף פעיל', startApproved: 'לחץ + או בחר פרופיל Shell כדי להתחיל ב-workspace מאושר.', terminalWindow: 'מסוף OrPAD', loadingWorkspace: 'טוען workspace...', dockMain: 'הצמד לחלון הראשי', noWorkspace: 'עדיין אין workspace מאושר',
    aiReady: 'סרגל הצד של AI מוכן.', aiReadyDoc: 'AI מוכן עבור {name}', aiDocPrompt: 'בקש כתיבה מחדש, הסבר או המרת פורמט עם המסמך הנוכחי כהקשר.', aiGeneralPrompt: 'שאל שאלה כללית או פתח מסמך כדי לצרף הקשר קובץ.', noActive: 'אין מסמך פעיל. Chat עדיין עובד; פתח קובץ כדי לצרף הקשר.', providerSettings: 'הגדרות AI Provider', newChat: 'Chat חדש', rename: 'שנה שם', search: 'חיפוש', send: 'שלח', stop: 'עצור', waiting: 'ממתין לתגובת AI...', assist: 'כלי Assist', noActiveTitle: 'אין מסמך פעיל.', openDocTools: 'פתח לשונית CSV, JSON, Markdown או Mermaid כדי לראות כלים מקומיים ו-AI.',
    mcpServers: 'שרתי MCP', mcpSubtitle: 'הפעל שרת ואז פתח Tools או Resources. Tool calls תמיד דורשים הרשאה.', desktopOnly: 'MCP זמין רק ב-desktop.', desktopOnlyBody: 'פתח את אפליקציית Electron כדי להתחבר לשרתי MCP מקומיים.', noMcp: 'לא הוגדרו שרתי MCP.', addImport: 'הוסף שרת או יבא הגדרת MCP כדי להתחיל.', refresh: 'רענן', add: 'הוסף', edit: 'ערוך', export: 'יצא', import: 'יבא', enable: 'הפעל', disable: 'השבת', running: 'פועל', starting: 'מתחיל', stopped: 'נעצר',
  },
};

const aliases = {};

function fromPack(p) {
  return {
    'terminal.title': p.terminal,
    'terminal.subtitle': p.terminalSubtitle,
    'terminal.mode.terminal': p.terminal,
    'terminal.new.title': p.newTerminal,
    'terminal.new.subtitle': p.chooseShell,
    'terminal.empty.title': p.noTerminal,
    'terminal.empty.subtitle': p.startApproved,
    'terminal.window.title': p.terminalWindow,
    'terminal.window.loadingWorkspace': p.loadingWorkspace,
    'terminal.window.dockToMain': p.dockMain,
    'terminal.window.noWorkspace': p.noWorkspace,
    'ai.empty.ready': p.aiReady,
    'ai.empty.readyWithDoc': p.aiReadyDoc,
    'ai.empty.readyPromptWithDoc': p.aiDocPrompt,
    'ai.empty.readyPromptNoDoc': p.aiGeneralPrompt,
    'ai.context.none': p.noActive,
    'ai.provider.settingsTitle': p.providerSettings,
    'ai.history.new': p.newChat,
    'ai.history.rename': p.rename,
    'ai.history.searchPlaceholder': p.search,
    'ai.history.newChat': p.newChat,
    'ai.send': p.send,
    'ai.stop': p.stop,
    'ai.message.waiting': p.waiting,
    'ai.actions.titleDefault': p.assist,
    'ai.actions.noActiveTitle': p.noActiveTitle,
    'ai.actions.noActiveBody': p.openDocTools,
    'mcp.title': p.mcpServers,
    'mcp.subtitle': p.mcpSubtitle,
    'mcp.desktopOnlyTitle': p.desktopOnly,
    'mcp.desktopOnlyBody': p.desktopOnlyBody,
    'mcp.noServersTitle': p.noMcp,
    'mcp.noServersBody': p.addImport,
    'mcp.refresh': p.refresh,
    'mcp.add': p.add,
    'mcp.edit': p.edit,
    'mcp.export': p.export,
    'mcp.import': p.import,
    'mcp.enable': p.enable,
    'mcp.disable': p.disable,
    'mcp.running': p.running,
    'mcp.starting': p.starting,
    'mcp.stopped': p.stopped,
  };
}

export const extraLocales = {};
for (const [code, pack] of Object.entries({ ...packs, ...aliases })) {
  if (pack) extraLocales[code] = fromPack(pack);
}
